#!/usr/bin/env python3

def ingest_pypdf(pdf_path: str, out_path: str = ""):
    ...

def ingest_di(pdf_path: str, out_path: str = ""):
    ...

def chunk(document):
    ...

def create_index(index_name: str):
    ...

def index_chunks(chunks: list[dict], index_name: str):
    ...

def search(search_text: str, document_id: str = "", top: int = 5):
    ...

def chat(question: str, context: str):
    ...

def ask(question: str, document_id: str = ""):
    ...
    
