[project]
name = "twoday-si26-ai-kurs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "azure-ai-documentintelligence>=1.0.2",
    "azure-identity>=1.25.3",
    "azure-search-documents>=12.0.0",
    "azure-storage-blob>=12.29.0",
    "openai>=2.38.0",
    "pypdf>=6.13.0",
    "python-dotenv>=1.2.2",
    "streamlit[pdf]>=1.58.0",
]
